# OG Tags and Related
title: DIE SOFT
description: A tiny indie game studio working on 'Little Nemo and the Guardians of Slumberland'
image: /assets/images/diesoft.logomark.png
type: website
twitter:
  username: diesoftgames
  card: summary

email: "diesoftgames@gmail.com"
twitter_username: "diesoftgames"

google_analytics: G-CQW2YSYWZL
contact_email: "contact@diesoft.games"
discord_url: "https://discord.com/invite/9NymgSJAVp"
twitter_url: "https://twitter.com/diesoftgames"
mailchimp_url: "http://eepurl.com/hZcvJP"
tiktok_url: "https://tiktok.com/@diesoftgames"
steam_url: "https://store.steampowered.com/app/2074630/Little_Nemo_and_the_Guardians_of_Slumberland?utm_source=homepage"
revue_url: "https://www.getrevue.co/profile/diesoftgames?via=website"
press_Kit: "https://drive.google.com/drive/folders/1nzbgOSApIRX2Zk6OJsMvCf6nSgHoXqdY?usp=sharing"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "markdown-container"
  -
    scope:
      path: "/_posts"
    values:
      layout: "post"