# OG Tags and Related
title: "DIE SOFT"
description: "A tiny indie game studio working on 'Little Nemo and the Guardians of Slumberland'"
image: "/assets/images/diesoft.logomark.png"
type: "website"
twitter:
  username: diesoftgames
  card: summary

email: "diesoftgames@gmail.com"
twitter_username: "diesoftgames"

google_analytics: G-CQW2YSYWZL
mailchimp_url: "http://eepurl.com/hZcvJP"
revue_url: "https://www.getrevue.co/profile/diesoftgames?via=website"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "markdown-container"
  -
    scope:
      path: "/_posts"
    values:
      layout: "post"